export const batch1 = [
    {
        title: 'Chuyện cái DMS và nỗi đau "quản quân" của sếp Việt',
        slug: { current: 'dms-noi-dau-quan-quan' },
        publishedAt: new Date().toISOString(),
        excerpt: 'Sáng nay Hải ngồi cafe với mấy ông bạn chủ doanh nghiệp. Ông nào cũng than trời: "Quân anh nó đi thị trường kiểu gì mà doanh số cứ lẹt đẹt, trong khi báo cáo thì đẹp như mơ!". Thế là Hải phải ra tay "giải ngố" vụ DMS.',
        categorySlug: 'digital-transformation',
        coverImage: '/blog/dms_noi_dau_quan_quan.png',
        featured: true,
        readingTime: 20,
        tags: ['DMS', 'Quản trị Sales', 'Chuyển đổi số', 'Góc nhìn HaiLP', 'SME', 'Sales Tricks'],
        body: [
            {
                _type: 'block',
                style: 'normal',
                children: [{ _type: 'span', text: 'Chào các bạn, lại là Hải đây. Sáng nay Sài Gòn mưa tầm tã, ngồi cafe cóc ở góc đường Pasteur mà nghe mấy ông bạn giám đốc than thở thấy thương. Chuyện là vầy: nuôi đội sale 50 mạng, lương cứng trả đều, xăng xe bao trọn, KPI thưởng phạt phân minh, mà cuối tháng số về không đủ tiền điện nước.' }],
            },
            {
                _type: 'block',
                style: 'normal',
                children: [{ _type: 'span', text: 'Hải mới hỏi nhẹ một câu: "Thế mấy ổng đi đâu làm gì tụi ông có biết không?". Mấy ổng ngớ người nhìn nhau: "Thì nó check-in Zalo, chụp hình tiệm tạp hóa gửi về group công ty mà, định vị rõ ràng đấy thôi".' }],
            },
            {
                _type: 'block',
                style: 'normal',
                children: [{ _type: 'span', text: 'Trời ơi là trời! Thời đại AI ầm ầm rồi mà các sếp còn quản lý bằng "niềm tin" trên Zalo thì chỉ có bán nhà sớm. Các bạn có biết cái định vị Zalo hay Google Maps gửi qua tin nhắn nó "ảo" cỡ nào không? Chỉ cần ngồi một chỗ, dùng mấy cái app Fake GPS miễn phí đầy trên mạng, là muốn check-in ở Mỹ cũng được chứ đừng nói là tiệm tạp hóa dì Bảy cách đó 5km.' }],
            },
            {
                _type: 'block',
                style: 'normal',
                children: [{ _type: 'span', text: 'Để Hải kể cho nghe cái "thế giới ngầm" của dân sale thị trường, những mánh lới mà nếu không lăn lộn 10 năm trong nghề thì không bao giờ các bạn biết được. Và rồi, Hải sẽ chỉ cho các bạn cái "bảo bối" tên là DMS (Distribution Management System) - thứ mà nếu dùng đúng, nó sẽ là "camera chạy bằng cơm" tốt nhất cho doanh nghiệp.' }],
            },
            {
                _type: 'block',
                style: 'h2',
                children: [{ _type: 'span', text: '1. Muôn kiểu "qua mặt" sếp (Đọc để kìm nén cơn giận)' }],
            },
            {
                _type: 'block',
                style: 'normal',
                children: [{ _type: 'span', text: 'Các bạn sale nhà mình thông minh lắm, nhanh nhạy lắm. Nhưng tiếc là nhiều khi sự thông minh ấy lại dùng để đối phó với công ty. Dưới đây là 3 chiêu kinh điển:' }],
            },
            {
                _type: 'block',
                style: 'normal',
                listItem: 'bullet',
                children: [{ _type: 'span', text: 'Chiêu 1 - Check-in "giả cầy": Đây là chiêu sơ đẳng nhất. Sáng dậy trễ, trời mưa, ngại ra đường. Thế là bật máy lạnh nằm nhà, mở app Fake GPS, chỉnh tọa độ ra đúng cửa hàng cần viếng thăm. Xong lôi trong máy ra tấm hình chụp cái bảng hiệu cửa hàng (đã chụp dự trữ từ tháng trước), gửi lên group báo cáo: "Em đã đến điểm!". Sếp ở nhà thấy định vị chuẩn, hình ảnh có, khen lấy khen để: "Thằng này chăm chỉ!". Thực tế nó đang ngủ nướng.' }],
            },
            {
                _type: 'block',
                style: 'normal',
                listItem: 'bullet',
                children: [{ _type: 'span', text: 'Chiêu 2 - "Xào" tồn kho (Inventory Cooking): Chiêu này hại công ty kinh khủng. Hàng trong kho đại lý thực tế còn đầy nhóc (do không bán được). Nhưng sale muốn ép công ty đẩy hàng mới xuống (sell-in) để đạt chỉ tiêu doanh số tháng. Thế là trong báo cáo tồn kho gửi về, sale ghi khống là "Hết hàng". Công ty thấy hết hàng thì mừng quá, xuất ngay lô mới xuống. Kết quả: Kho đại lý vỡ trận, hàng cũ hết date, hàng mới không chỗ để. Đại lý chửi công ty, công ty mất tiền hủy hàng.' }],
            },
            {
                _type: 'block',
                style: 'normal',
                listItem: 'bullet',
                children: [{ _type: 'span', text: 'Chiêu 3 - "Gửi hàng" (Dumping): Để đạt thưởng quý, sale năn nỉ đại lý: "Anh chị nhập giùm em 100 thùng đi, tháng sau em bán bù cho". Đại lý nể tình nhập vào. Tháng sau sale... nghỉ việc. Để lại đống hàng đó cho người mới lãnh đủ. Người mới vào thấy thị trường "ngập lụt", bán không được, lại nghỉ. Một cái vòng luẩn quẩn chết người.' }],
            },
            {
                _type: 'block',
                style: 'h2',
                children: [{ _type: 'span', text: '2. DMS - Không phải thuốc tiên, nhưng là "Vòng Kim Cô"' }],
            },
            {
                _type: 'block',
                style: 'normal',
                children: [{ _type: 'span', text: 'Nghe xong mấy chiêu trên chắc các sếp nóng mặt rồi. Vậy trị thuốc gì? Zalo không trị được, Excel càng không. Chỉ có DMS.' }],
            },
            {
                _type: 'block',
                style: 'normal',
                children: [{ _type: 'span', text: 'DMS (Distribution Management System) hiểu nôm na là một phần mềm chuyên dụng quản lý hệ thống phân phối. Nó cài trên điện thoại nhân viên sale và máy tính của sếp/kế toán. Nó làm được gì?' }],
            },
            {
                _type: 'block',
                style: 'normal',
                listItem: 'number',
                children: [{ _type: 'span', text: 'Giám sát hành trình (Route Strictness): DMS hiện đại nó khôn lắm. Nó bắt buộc sale phải đứng đúng tại vị trí cửa hàng (sai số tối đa 50m) mới cho phép bấm nút "Bắt đầu viếng thăm". Không Fake GPS được vì nó check cả Mock Location của Android. Đang ở quán cafe cách đó 500m là nút bấm nó ẩn đi ngay.' }],
            },
            {
                _type: 'block',
                style: 'normal',
                listItem: 'number',
                children: [{ _type: 'span', text: 'Chụp hình Real-time: Muốn báo cáo trưng bày? Phải chụp trực tiếp từ camera của App DMS. Không cho phép upload ảnh từ thư viện (Gallery). Thế là hết đường dùng ảnh cũ.' }],
            },
            {
                _type: 'block',
                style: 'normal',
                listItem: 'number',
                children: [{ _type: 'span', text: 'Automation Order: Đặt hàng trên app, số nhảy về ERP/Kế toán ngay lập tức. Tính khuyến mãi tự động, không lo sale tính nhầm hay cố tình "ăn gian" khuyến mãi của đại lý.' }],
            },
            {
                _type: 'block',
                style: 'h2',
                children: [{ _type: 'span', text: '3. Bài học xương máu của Hải khi triển khai DMS' }],
            },
            {
                _type: 'block',
                style: 'normal',
                children: [{ _type: 'span', text: 'Ngày xưa Hải mới làm Giám đốc kinh doanh, máu lửa lắm. Đề xuất công ty mua gói DMS ngoại, tốn cả trăm nghìn đô. Hí hửng đem về áp dụng. Kết quả? Thất bại thảm hại.' }],
            },
            {
                _type: 'block',
                style: 'normal',
                children: [{ _type: 'span', text: 'Anh em sale phản ứng dữ dội. Họ bảo: "Công ty không tin tưởng tụi em", "Cài cái này theo dõi như tội phạm", "Pin đâu mà chịu nổi". Đỉnh điểm là cả đội sales đình công, dọa nghỉ việc. Hải sợ xanh mặt, phải tạm dừng dự án.' }],
            },
            {
                _type: 'block',
                style: 'normal',
                children: [{ _type: 'span', text: 'Rút kinh nghiệm sâu sắc: Công nghệ chỉ là cái xác (Tools), CON NGƯỜI mới là cái hồn (Mindset). Muốn làm DMS thành công, phải "dân vận" trước. Phải làm tư tưởng cho anh em:' }],
            },
            {
                _type: 'block',
                style: 'blockquote',
                children: [{ _type: 'span', text: '"Các em ơi, cái App này không phải để anh soi các em. Nó giúp các em không phải ghi chép sổ sách tay, không phải cộng trừ nhân chia khuyến mãi nhức đầu, tối về không phải làm báo cáo Excel nữa. Bấm một cái là xong, về sớm với vợ con. Công ty đầu tư tiền tấn là để giải phóng sức lao động cho các em cơ mà!".' }],
            },
            {
                _type: 'block',
                style: 'normal',
                children: [{ _type: 'span', text: 'Nói lọt tai, thấy quyền lợi sát sườn, thì họ mới dùng. Mà họ chịu dùng thì mình mới có số liệu.' }],
            },
            {
                _type: 'block',
                style: 'h2',
                children: [{ _type: 'span', text: 'Lời kết cho buổi sáng' }],
            },
            {
                _type: 'block',
                style: 'normal',
                children: [{ _type: 'span', text: 'Làm sếp ngành phân phối ở Việt Nam là một nghề "bạc đầu". Nhưng "khổ" mà quản lý được, ra tiền, tối ngủ ngon thì cũng đáng. Các bạn CEO, CSO đang đọc bài này, hãy tỉnh táo lại đi. Đừng quản lý bằng cảm tính, bằng "tin nhau là chính" nữa. Số liệu (Data) không biết nói dối đâu.' }],
            },
            {
                _type: 'block',
                style: 'normal',
                children: [{ _type: 'span', text: 'Nếu công ty bạn chưa có DMS, hãy tìm hiểu ngay. Nếu đã có mà dùng chưa hiệu quả, hãy xem lại cách "dân vận" của mình. Chúc các bạn một ngày năng lượng và chốt đơn ầm ầm!' }],
            },
        ],
    },
    {
        title: 'Chuyện bà bán tạp hóa và bài toán RTM "nhức não"',
        slug: { current: 'ba-ban-tap-hoa-va-rtm' },
        publishedAt: new Date(Date.now() - 86400000).toISOString(),
        excerpt: 'RTM (Route-to-Market) nghe sang chảnh vậy thôi, chứ thực ra là chuyện "làm sao đem gói mì tôm từ kho ra tới tay bà Bảy đầu ngõ" mà tốn ít tiền xăng nhất. Bài toán lợi nhuận nằm ở đây chứ đâu.',
        categorySlug: 'strategic-leadership',
        coverImage: '/blog/ba_ban_tap_hoa_rtm.png',
        featured: true,
        readingTime: 25,
        tags: ['RTM', 'Logistics', 'Cost-to-Serve', 'Profit', 'FMCG', 'Góc nhìn HaiLP'],
        body: [
            {
                _type: 'block',
                style: 'normal',
                children: [{ _type: 'span', text: 'Hồi Hải mới chân ướt chân ráo đi làm cho một tập đoàn đa quốc gia, Hải giữ vị trí là "SFA Specialist" (Chuyên viên SFA). Ngày ấy công ty đang có chiến dịch rất oách: "National Coverage Expansion" (Mở rộng độ phủ toàn quốc).' }],
            },
            {
                _type: 'block',
                style: 'normal',
                children: [{ _type: 'span', text: 'Sếp Sales Director thì hô hào quân đi mở đất. Còn ông Sếp Tây của Hải thì giao cho Hải một nhiệm vụ thầm lặng hơn: "Hey Hai, mày dùng Data soi xem tụi Sales mở thị trường có hiệu quả không, hay là đang đốt tiền?".' }],
            },
            {
                _type: 'block',
                style: 'normal',
                children: [{ _type: 'span', text: 'Lúc đầu, anh em Sales hừng hực khí thế lắm. Tuyển thêm người, chạy loạn xạ. Phương châm là: "Thà giết nhầm hơn bỏ sót". Ai mua cũng bán, 1 thùng mì cũng giao tít tận Củ Chi.' }],
            },
            {
                _type: 'block',
                style: 'normal',
                children: [{ _type: 'span', text: 'Cuối năm tổng kết. Doanh số tăng gấp đôi (Yeah!). Ông Sales Director hí hửng chờ Sếp khen. Nhưng không, Sếp Finance đưa ra tờ báo cáo đỏ lòm: "Lợi nhuận âm! Cost-to-Serve (Chi phí phục vụ) cao quá!". Hóa ra tiền lời bán thùng mì không đủ bù tiền xăng xe và tiền lương sales chạy đi giao.' }],
            },
            {
                _type: 'block',
                style: 'h2',
                children: [{ _type: 'span', text: 'Cái bẫy "Cost-to-Serve": Khi bán hàng là... làm từ thiện' }],
            },
            {
                _type: 'block',
                style: 'normal',
                children: [{ _type: 'span', text: 'Các bạn trẻ làm sale hay mắc bệnh thành tích (Topline Obsession). Thấy bán được hàng là sướng, bất chấp giá nào. Nhưng các bạn quên mất một điều cơ bản: Bán hàng TỐN TIỀN (Selling Cost).' }],
            },
            {
                _type: 'block',
                style: 'normal',
                children: [{ _type: 'span', text: 'Hãy làm một bài toán nhỏ. Để giao 1 thùng mì trị giá 100k cho tiệm tạp hóa bà Bảy ở tít Củ Chi, bạn tốn những gì?' }],
            },
            {
                _type: 'block',
                style: 'normal',
                listItem: 'bullet',
                children: [{ _type: 'span', text: 'Tiền lương nhân viên sale ghé thăm: 30 phút chém gió với bà Bảy = 50k.' }],
            },
            {
                _type: 'block',
                style: 'normal',
                listItem: 'bullet',
                children: [{ _type: 'span', text: 'Tiền xăng xe tải giao hàng: Chạy đi chạy về 40km = 100k xăng + khấu hao.' }],
            },
            {
                _type: 'block',
                style: 'normal',
                listItem: 'bullet',
                children: [{ _type: 'span', text: 'Tiền xử lý đơn hàng, kế toán, in hóa đơn, bốc xếp kho bãi...: 20k nữa.' }],
            },
            {
                _type: 'block',
                style: 'normal',
                children: [{ _type: 'span', text: 'Tổng chi phí "vô hình" để phục vụ đơn hàng đó là 170k. Trong khi lãi gộp (Gross Margin) của thùng mì đó chỉ có 20k. Tức là công ty đang LỖ chỏng gọng 150k cho mỗi lần bạn bán thùng mì đó cho bà Bảy!' }],
            },
            {
                _type: 'block',
                style: 'normal',
                children: [{ _type: 'span', text: 'Đấy, bán hàng kiểu đó thì thà ở nhà ngủ cho khỏe, càng bán càng lỗ. Đó là bài học đầu đời của Hải về RTM.' }],
            },
            {
                _type: 'block',
                style: 'h2',
                children: [{ _type: 'span', text: 'Giải pháp từ Data: Phân loại hay là chết?' }],
            },
            {
                _type: 'block',
                style: 'normal',
                children: [{ _type: 'span', text: 'Với vai trò là SFA Specialist, Hải không chấp nhận cách làm "chạy bằng cơm" đó. Hải đã dùng dữ liệu để phân loại khách hàng (Segmentation):' }],
            },
            {
                _type: 'block',
                style: 'normal',
                listItem: 'number',
                children: [{ _type: 'span', text: 'Khách VIP (Gold): Mua sỉ, tiền tươi -> Chăm sóc tận răng, xe tải giao hàng ưu tiên.' }],
            },
            {
                _type: 'block',
                style: 'normal',
                listItem: 'number',
                children: [{ _type: 'span', text: 'Khách Tiềm năng (Silver): Mua đều -> Ghé thăm tuần/lần.' }],
            },
            {
                _type: 'block',
                style: 'normal',
                listItem: 'number',
                children: [{ _type: 'span', text: 'Khách Rêu (Bronze - Hay gọi vui là "Khách hành"): Mua lắt nhắt, xa xôi -> CẮT phục vụ trực tiếp! Chuyển sang Telesales hoặc yêu cầu tự đến lấy hàng (Cash & Carry). Nếu họ không chịu? Thì thôi chia tay.' }],
            },
            {
                _type: 'block',
                style: 'h2',
                children: [{ _type: 'span', text: 'Kết quả bất ngờ từ sự tàn nhẫn' }],
            },
            {
                _type: 'block',
                style: 'normal',
                children: [{ _type: 'span', text: 'Khi Hải tư vấn cho sếp cắt bỏ phục vụ trực tiếp cho 40% lượng khách hàng nhóm Bronze, anh em sale phản đối ghê lắm, sợ mất số. Nhưng sếp Tây nghe theo Data.' }],
            },
            {
                _type: 'block',
                style: 'normal',
                children: [{ _type: 'span', text: 'Kết quả sau 6 tháng: Doanh số tổng giảm nhẹ 10% (do mất khách nhỏ). Nhưng LỢI NHUẬN RÒNG (Net Profit) tăng vọt 30%. Sếp Tây vỗ đùi cái đét: "Brilliant job, Hai!".' }],
            },
            {
                _type: 'block',
                style: 'normal',
                children: [{ _type: 'span', text: 'Bài học ở đây là: Đừng tham to. Hãy tham hiệu quả. Làm kinh doanh là phải thực dụng, đừng lãng mạn hóa con số doanh thu. Doanh thu là Phù du (Vanity), Lợi nhuận mới là Thực tế (Sanity).' }],
            },
            {
                _type: 'block',
                style: 'normal',
                children: [{ _type: 'span', text: 'Các bạn hãy thử về công ty, tải cái file Excel bán hàng ra, tính thử Cost-to-Serve cho từng khách hàng xem. Hải cá là các bạn sẽ giật mình, có những khách hàng các bạn đang "nuôi báo cô" mà không biết đấy. Mạnh dạn cắt bỏ cành sâu để cây lớn nhanh nhé!' }],
            },
        ],
    }
];
